#!/usr/bin/env python3
"""Largest classes by line count

Generated by ast-skill-create. A thin skill on top of the harness: it declares
what to match (node kinds ['class_declaration'] in typescript, tsx, javascript) and lets the shared engine do the scanning,
nested-match folding, naming, ranking, and table printing. The calling agent
only ever sees the small table at the end, never the raw AST.

Usage:
    python -m sniff.detectors.large_classes [PATH] [--top N] [--lang L ...] [--include-tests]
"""

from __future__ import annotations

import argparse
import sys

from sniff import harness as h

# What counts as a match. Either a {language: [node kinds]} map or an ast-grep
# pattern string; the harness accepts both. (Filled in by the create.)
RULE = {'typescript': ['class_declaration'], 'tsx': ['class_declaration'], 'javascript': ['class_declaration']}

# Plural noun for the header, e.g. "classes", "functions", "switch statements".
NOUN = "classes"

NAME = "large-classes"
TITLE = "Largest classes"
DEFAULT_ARGS: "list[str]" = []


def main(argv: "list[str] | None" = None) -> int:
    parser = argparse.ArgumentParser(description="Largest classes by line count")
    parser.add_argument("path", nargs="?", default=".", help="directory to scan (default: .)")
    parser.add_argument("--top", type=int, default=10, help="how many to show (default: 10)")
    parser.add_argument("--lang", action="append", help="force a language (repeatable); skips auto-detect")
    parser.add_argument("--include-tests", action="store_true", help="include *.spec.* / *.test.* files")
    parser.add_argument("--extra-ignore", action="append", default=[],
                        help="glob to exclude, relative to PATH (repeatable)")
    args = parser.parse_args(argv)

    langs = sorted(set(args.lang)) if args.lang else sorted(h.detect_languages(args.path, args.extra_ignore))
    if not langs:
        sys.exit(f"No supported source files found under {args.path!r}.")

    matches = h.run(RULE, args.path, lang=langs, include_tests=args.include_tests,
                     extra_ignores=args.extra_ignore)
    matches = h.fold_nested(matches)

    if not matches:
        print(f"No {NOUN} matched.")
        return 0

    header = (
        f"Largest {min(args.top, len(matches))} of {len(matches)} {NOUN} "
        f"({', '.join(langs)}; tests {'included' if args.include_tests else 'excluded'}; "
        f"nested matches folded into their parent):"
    )

    h.print_table(
        matches,
        columns=[
            ("LINES", lambda m: m.lines),
            ("NAME", lambda m: m.name),
            ("LOCATION", lambda m: m.location),
        ],
        sort_key=lambda m: m.lines,
        top=args.top,
        header=header,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
