#!/usr/bin/env python3
"""Largest classes by line count

Generated by ast-skill-create. A thin skill on top of the harness: it declares
what to match (node kinds ['class_declaration'] in typescript, tsx, javascript) and lets the shared engine do the scanning,
nested-match folding, naming, ranking, and table printing. The calling agent
only ever sees the small table at the end, never the raw AST.

Usage:
    python -m sniff.detectors.large_classes [PATH] [--top N] [--lang L ...] [--include-tests]
"""

from __future__ import annotations

import sys

from sniff.detectors import _node_metric_cli as cli

# What counts as a match. Either a {language: [node kinds]} map or an ast-grep
# pattern string; the harness accepts both. (Filled in by the create.)
# Python spells its class node `class_definition`, not `class_declaration`.
RULE = {
    'typescript': ['class_declaration'],
    'tsx': ['class_declaration'],
    'javascript': ['class_declaration'],
    'python': ['class_definition'],
}

# The languages this detector has node kinds for; every other language is
# reported as out of scope rather than silently scanned and found empty.
LANGUAGES = sorted(RULE)

# Plural noun for the header, e.g. "classes", "functions", "switch statements".
NOUN = "classes"

NAME = "large-classes"
TITLE = "Largest classes"
DEFAULT_ARGS: "list[str]" = []


def main(argv: "list[str] | None" = None) -> int:
    parser = cli.new_parser("Largest classes by line count")
    cli.finish_parser(parser)
    args = parser.parse_args(argv)

    langs = cli.detect_and_gate(args, LANGUAGES)
    if langs is None:
        return 0

    return cli.run_size_main(
        args, langs, RULE,
        header=lambda shown, total, langs_str, tests_str: (
            f"Largest {shown} of {total} {NOUN} "
            f"({langs_str}; tests {tests_str}; nested matches folded into their parent):"
        ),
        empty_message=f"No {NOUN} matched.",
    )


if __name__ == "__main__":
    sys.exit(main())
